### ISSUE TITLE
Speaking JavaScript

### ISSUE THREAD

**Issue by EmilyMB** [turingschool/intermission-assignments#12]
Discuss [Speaking JavaScript](http://speakingjs.com/es5/), especially following chapters here:
- [Chapter 3: The Nature of JavaScript](http://speakingjs.com/es5/ch03.html)
- [Chapter 15: Functions](http://speakingjs.com/es5/ch15.html)
- [Chapter 16: Variables: Scopes, Environments, and Closures](http://speakingjs.com/es5/ch16.html)
- [Chapter 17: Objects and Inheritance](http://speakingjs.com/es5/ch17.html)

**Comment by EmilyMB** [comment]
I'm finding Chapter 15 hard to digest...anyone else running into that issue? After a while all the terms seems to coalesce into a mush heap of gobbledy goop.

**Comment by nathanows** [comment]
Chapter 3: 
- The silent failing seems... annoying (I'm sure that's improving, but still)
- Ugh, JS floating point numbers... not fun

Chapter 15:
- The named function thing is kind of cool from a recursion perspective (and what isn't from that perspective?)
- Function hoisting seems convenient but possibly confusing in that you'll have to trace back where a function was defined.
- I'm not sure I completely understand the differences between a function declaration and assigning an anonymous function to a variable, and when you should use one or the other.
- I don't think i realized map was a JS thing as well... nice
- JS named parameters a syntactically annoying...

Chapter 16:
- The scope leak in something like condition stmts seems potentially really annoying, and the IIFE workaround seems pretty hacky
- In JS i've written in the past, I've found global variables really hard not to use... the recommended use of IIFE makes sense, but seems cumbersome
- I've found this article helpful for understanding closures: http://javascriptissexy.com/understand-javascript-closures-with-ease/

Chapter 17 (aka, `var couldThisChapterBeLonger = false;`)
- I complained on the thoughtbot style guide about them recommending a trailing comma on the last item in a list, the description here might have changed my mind.... "A trailing comma is useful, because you can rearrange properties without having to worry which property is last."

**Comment by Jwan622** [comment]
I don't get prototypes. Why is this:

function Person(name) {
    this.name = name;
}
The object in Person.prototype becomes the prototype of all instances of Person. It contributes part 2:
Person.prototype.describe = function () {
    return 'Person named '+this.name;
};
Let’s create and use an instance of Person:

> var jane = new Person('Jane');
> jane.describe()
> 'Person named Jane'

Specifically, I don't get this line:

The object in Person.prototype becomes the prototype of all instances of Person.

**Comment by bmrsny** [comment]
I think prototypes are sticking in a little more. I was confused on when to use a constructor verse a prototype. 
So I think the problem with Constructors is that when using a constructor like var person1 =  New Person, it creates the methods for each object.  Versus using a prototype which will use the same methods for all objects, better on performance or memory possibly too.
