### ISSUE TITLE
The Birth and Death of Javascript by Gary Bernhardt (optional)

### ISSUE THREAD

**Issue by worace** [turingschool/intermission-assignments#32]
[The Birth and Death of Javascript by Gary Bernhardt](https://www.destroyallsoftware.com/talks/the-birth-and-death-of-javascript) - This talk takes a tongue-in-cheek tone, but the concepts discussed are very topical. What does Bernhardt suggest about the role of Javascript in shaping the modern web?

**Comment by hhoopes** [comment]
I wanted to watch this talk because my husband gives me a hard time about learning JavaScript (pronounced "Yava-script..."), often citing how quickly it was written and how terrible of a language it is. 

I am still conflicted about the final point that Bernhardt makes, that JavaScript's dominance of the industry whether the web or (as extrapolated to the future) as a basis for all our systems is fundamentally because JS was both popular and bad. I feel my personal takeaway is that I may not enjoy JS, it may not be the best tool for the job, but I basically have to learn to write JS because that is what the industry expects me to know. It also seems that some of its popularity is simply because developers are lazy (wanting to use it for everything instead of multiple languages). It seems inertia and laziness are bad criteria to build upon, especially when you need to hide a language's flaws by creating other frameworks over it. 

Still, I am curious about asm and how it's used, and would like to get a better sense of what about JS creates the future that Bernhadt predicts. 
- "The behavior you see a tool being used for is a behavior that language encourages" (referring to Node's highly nested callbacks when used for both front and back end development)
- "Your bank is running a lot of JavaScript..."
