### ISSUE TITLE
Listen to Shop Talk with Tom Dale

### ISSUE THREAD

**Issue by stevekinney** [turingschool/intermission-assignments#4]
**Listen**: [Shop Talk: Tom Dale](http://shoptalkshow.com/episodes/147-tom-dale/) (1.5 hours)
- Do you agree with Tom? 
- What parts of his argument are compelling?
- What parts do you disagree with?

**Comment by ghost** [comment]
I find Tom's assertion that client side computing power is substantially underused is essentially true.  Not having much knowledge of javascript or a js framework, I'm not qualified to speak on how easily combining front and back end services might be realized.  I'm curious about how one keeps server and client side data in sync, something that wasn't really touched on and I imagine could be problematic with large sets.  Also, it seems that the MVC model might on both sides might have a) substantial overlap, and b) duplication of responsibilities, neither of which were really discussed.  Notwithstanding that, listening to Changelog and other podcasts where node.js was discussed, if js frameworks can deliver this kind of performance on both sides and it scales (i.e Black Friday for Walmart), I'm not sure where that leaves Rails.  Granted, Tom did have some less than encouraging things to say about meteor.js (the current new hotness), which I thought was interesting.

**Comment by ghost** [comment]
Also, seriously impressed that he went from Apple Store Genius to javascript code base maintainer in something like 4 months of just diligent reading of js books and mucking about with the codebase.  Find that slightly fantastic.

**Comment by dglunz** [comment]
Tom (I think it was Tom, I can never keep track of podcast voices) brings up a great point that your iPhone has more computing power than the typical EC2 instance. Offloading computing onto the client sounds great in theory, but like David mentioned, keeping data in sync could be problematic. Despite the concern, he sold me pretty quickly on the idea of using a Front End JS Framework.

The Ember Inspector Tool sounds fucking awesome. It sounds like I can just as easily ~~steal~~ get inspiration from other apps the same way I do CSS.  

I used Meteor in a project last summer. I knew nothing (still don't) about node or mongo so it made everything much more digestible. I always compare it to Rails because it does so many automagically things for you which can be a blessing or added confusion. I would recommend it but then again I'm not as qualified as Tom Dale. 

I second the impressiveness of going from Apple Store Genius to Javascript Wizard (he still doubted his skill but seems like he was) in 4 months. Sounds like he was thrown into a sink or swim type situation and figured out how to swim.

**Comment by skuhlmann** [comment]
I'm sold too. @stevekinney is Ember an option for one of the group projects in module 4? 

I started an Ember tutorial on Friday. Didn't get too far along, but I was enjoying it. I got the inspector tool and mostly played with that. It's pretty incredible. Take a look at the site Tom was talking about:
http://www.bustle.com/ - it's pretty snappy.

**Comment by skuhlmann** [comment]
To clarify my question about Ember for module 4 project... An Ember front end backed by a rails app creating the APIs.

**Comment by stevekinney** [comment]
@skuhlmann Yes. We integrated a ton of feedback from the last two classes. FeedEngine will be a project with an Ember front-end and a Rails backend. You'll also have the option for the final community project to use Ember if you'd like. There is also a short new project at the beginning of the module tentatively called Game Time while we bone up on our Ember Fundamentals.

**Comment by VikiAnn** [comment]
Do you agree with Tom?
  Uh... that... Ember is a good idea? Sure? I guess? He seemed pretty enthusiastic about it.

What parts of his argument are compelling?
  I guess I didn't really realize he was arguing a point. Sounded like he was just talking about what it does in general. It sounds fast, and I guess fast is good, so I guess that's compelling.

What parts do you disagree with?
  I don't have any reason to disagree with anything. I'm terrible at JavaScript and terrified of it, but I have no reason to think it's a bad idea or anything.

**Comment by ghost** [comment]
+1 on everything @VikiAnn said.

**Comment by katelane** [comment]
I'm really, really excited to dig further into JS and get into Ember in module 4 after listening to that, woot!
