### ISSUE TITLE
Sandi Metz's rules for developers

### ISSUE THREAD

**Issue by rrgayhart** [turingschool/intermission-assignments#55]
Discuss Sandi Metz's Rules for Developers here.

Which of Sandi's rules do you feel like might be the hardest to follow—why?

**Comment by stevepentler** [comment]
https://gist.github.com/stevepentler/fdfa3b6f433be074b0f6

**Comment by SteveOscar** [comment]
https://gist.github.com/SteveOscar/4871c15f5fc6e5709328

**Comment by brantwellman** [comment]
https://gist.github.com/brantwellman/cc0e53736e1697a47f4b

**Comment by GregoryArmstrong** [comment]
https://gist.github.com/GregoryArmstrong/8249edaf6d071ebe3bb2

**Comment by ToniRib** [comment]
https://gist.github.com/ToniRib/54862ecac31aa8082f44

**Comment by ShannonPaige** [comment]
_Does this need to be a gist? I'm just gonna leave this here...._

I think the hardest rules to follow are:
**Methods can be no longer than five lines of code.**
The way my brain works, I want to put everything in one method and switch around using a bunch of cases or if/else statements. I've learned over the last 3 modules though, that this is a huge "smell" for me, and that it usually means I haven't broken the logic up enough and my method is doing too many things.

**Controllers can instantiate only one object.**
What!?!? I never heard this one before. I guess it makes sense, because you only want your class focusing on one object i.e have a single responsibility, but looking back on past projects, I pass a lot of stuff in. I'll have to start being more careful, and probably set up more classes, to make this work.

**Comment by PenneyGadget** [comment]
https://gist.github.com/PenneyGadget/879c53077621808adff2

**Comment by bethsebian** [comment]
https://gist.github.com/bethsebian/b7262bbe6c6fd65e0c56

**Comment by bethsecor** [comment]
https://gist.github.com/bethsecor/61e9965e8adf0336274c

**Comment by jecrockett** [comment]
https://gist.github.com/jecrockett/1eb387db113f65c6179e

**Comment by martensonbj** [comment]
https://gist.github.com/martensonbj/5843e2ec11423ade41a3

**Comment by dastinnette** [comment]
https://gist.github.com/dastinnette/3b13dddec2bd76b244a6

**Comment by Jpease1020** [comment]
https://gist.github.com/Jpease1020/81612cafc187549e5437

**Comment by hectorhuertas** [comment]
https://gist.github.com/hectorhuertas/0e80172c25a3a7c807c2

**Comment by jwperry** [comment]
https://gist.github.com/jwperry/6ca81f88e1133a6906b5

**Comment by afg419** [comment]
https://gist.github.com/afg419/6d13ce1b6813342d5293

**Comment by marlomajor** [comment]
https://gist.github.com/marlomajor/23b539e3b199dac84bad

**Comment by danjwinter** [comment]
https://gist.github.com/danjwinter/d902a2fb2f499fa7fbf4

**Comment by slota** [comment]
I think the hardest one to follow is the 5 lines, I get that clean code is nice but I think it's arbitrary. I was at React meetup this week and the guys speaking said they could care less about the lines of code which is much more my opinion so although its great having concise code, I will probably never be a stickler about it.

**Comment by Jlawlzz** [comment]
https://gist.github.com/Jlawlzz/ad78a643d69dff334620

**Comment by edgarduran** [comment]
https://gist.github.com/edgarduran/694566b63d40d4a09b52
