### ISSUE TITLE
jQuery fundamentals

### ISSUE THREAD

**Issue by rrgayhart** [turingschool/intermission-assignments#56]
Respond in the comments of this issue with:
1. What is something you learned that was particularly surprising/interesting?
2. What was something you already knew?
3. Was there anything you feel you still don't understand?

Feel free to ask any questions about jQuery fundamentals here as well.

**Comment by jecrockett** [comment]
Particularly Interesting: Much of the JavaScript Basics section was review for me, but I was really struck by one of the uses of logical operators to conditionally run a function: `a && b();`. I had never thought to use the operations in such a way, but it's a very easy way of saying something like `run_b_method if a`. You could also say `a || b();` is like `run_b_method unless a`. 

Already knew: I was already pretty comfortable with the concept of traversing the DOM so a lot of that section felt like review.

Still don't understand: The `$.Deferred` concept. I understand in theory what's happening and I get the point of promises, but I don't understand the inner workings enough to feel comfortable with it.

**Comment by ToniRib** [comment]
1. What is something you learned that was particularly surprising/interesting?
   - I found it interesting that there is no concept similar to 'attr_accessor' with JavaScript objects. Once an object is created, it's possible to modify any of its properties.
   - I also found it interesting that an empty string is falsy, but empty arrays and objects are not.
2. What was something you already knew?
   - That jQuery code should be wrapped within the $(document).ready() syntax so the code does not attempt to execute until all elements on the page are ready.
3. Was there anything you feel you still don't understand?
   - What's the point of using `end()` and `addBack()`? They seem like good ways to write really confusing code with chained methods instead of saving the various jQuery selections as variables and working with them separately.
   - Don't really understand JSONP. This didn't give a very good explanation of what it is and how it is different from JSON.

**Comment by SteveOscar** [comment]
1. It's interesting that in JavaScript, methods are object properties with a value of a function. In the way that you can call object.method in JS, it's like compacted version of calling a class method in Ruby.  I also didn't know that 0 is falsey.  
2. I already knew how to select DOM elements with jQuery.  
3. I'm confused about how to know which methods in jQuery are getter methods and which are setters.

**Comment by brantwellman** [comment]
Interesting: 
- JS variables not declared with `var` are global variables. Didn’t remember learning that before....and seems like a potential confusing bug just waiting to be stepped on by me. Mental note!
- jQuery chaining is cool, but easily creates confusion. Best to refactor out of it if you chain at all.

Already knew:
- How to select elements (but not much actual practice doing so).

Confused/don't understand:
- Getters operate on the first element in the selection, and Setters operate on all of the elements in the selection. I understand that…, but why? The difference seems arbitrary and creates confusion in my brain. And some methods are both getters and setters…(insert ‘confusion, my brain hurts emoji’)
- addBack() and end()....I’m confused as to why these concepts are introduced. The code examples with them seem far more confusing than the method of just storing selections in variables and manipulating them.

**Comment by stevepentler** [comment]
**What is something you learned that was particularly surprising/interesting?**
- Specific selection 
  ex: $('li').eq(1) to get the second list item without using an #id
  -I had no idea that you could chain events
  ex: calling a click function AND a key-up function on the same selector
- Expanding on that, you can pass in multiple events in a space separated string
  ex: $('li').on('click keydown', function()...

**What was something you already knew?**
- How to target selectors
- Filtering

**Was there anything you feel you still don't understand?**
- Why would you want to be able to style HTML with jQuery
- I haven't put much of this into practice, and using the chrome console to debug isn't comfortable yet. 
- It seems like there are a lot of options for AJAX and event listeners, and I struggle when there isn't a set convention.

**Comment by ShannonPaige** [comment]
**1. What is something you learned that was particularly surprising/interesting?**
- That due to hoisting, Function Expression is different from Function Declaration and can yield different results if you're not careful/explicit.
- You can force the meaning of _this_ to be what you want it to be, using the .call() or .apply() method on the function itself.
- When you call the $() function and pass a selector to it, you create a new jQuery object.

**2. What was something you already knew?**
- Local vs Global variable declaration
- That we could chain multiple methods in jQuery
- How to traverse the DOM
- Built-in effects

**3. Was there anything you feel you still don't understand?**
- I understand syntax, but its still hard for me to read/understand
- Event bubbling and delegation
- Returning data from ajax calls / jqXHR objects / deferreds

**Comment by PenneyGadget** [comment]
**1. What is something you learned that was particularly surprising/interesting?**
- That if you don't put <code>var</code> in front of your variable it will be global!
- It's weird that an empty string is falsy but empty array's and whatnot aren't. I also don't like that zero is false. It bugs me for some deep philosophical reason, haha. Although I did like how you can then use that to check if you got a matching element from your query by saying <code>if ($('#id').length)</code> because it will only run if it got a match and isn't zero.
- I thought it was neat that because jQuery stores a reference to your original selection you can traverse away from it and then get back to it with <code>.end()</code>.

**2. What was something you already knew?**
- I already knew some of the basics of traversal, but not to the degree that this tutorial gets into. 
- I knew about chaining methods and was familiar with the built in effects (though I've had very little practice with any of them).

**3. Was there anything you feel you still don't understand?**
- Like Shannon says above, I mostly get the syntax, but for some reason it's still all very hard for me to understand if it's not being explained line-by-line. This tutorial was mind-numbing for me.. I learn by doing, not by reading about it, so it felt like the more I read and the more complicated the concepts got the less I was understanding. 
- Event bubbling, delegation, deferreds, jqXHR, JSONP, much of ajax... like I said, my brain was getting mushier and retaining less, so by the last chapter I was hurting. 
- In Ruby we use <code>=</code> and <code>==</code> and in Javascript I thought it was <code>=</code> and <code>===</code> Come to find out Javascript has <code>=</code> and <code>==</code> AND <code>===</code> .. this is confusing to me. I read about the difference between <code>==</code> and <code>===</code> but I feel unclear about knowing which one to use where.
- I find <code>'use strict'</code> a bit bizarre - why not just use a linter in your editor?

**Comment by GregoryArmstrong** [comment]
1. What is something you learned that was particularly surprising/interesting?
   - You can manually trigger a JQuery event
   - Event Delegation allows for appending a list item to an existing list with events, and for that new list item to also have those already assigned events.
   - Hoisting. Allowing for declared functions to be used ahead of the actual declaration. Will take some getting used to as there's not much of that in Ruby/Rails.
2. What was something you already knew?
   - DOM Traversal
   - $(document).ready()
3. Was there anything you feel you still don't understand?
   - Deferreds, jqXHR

**Comment by bethsecor** [comment]
https://gist.github.com/bethsecor/6315353fddf7ffa902dd

**Comment by martensonbj** [comment]
https://gist.github.com/martensonbj/9d7bc8798257a59ed24f

**Comment by Jpease1020** [comment]
https://gist.github.com/Jpease1020/437cf3bd346233c845e5

**Comment by hectorhuertas** [comment]
https://gist.github.com/hectorhuertas/5016b441c5437ce77b6c

**Comment by jwperry** [comment]
https://gist.github.com/jwperry/1b4ff3e8ca832a14be21

**Comment by dastinnette** [comment]
https://gist.github.com/dastinnette/3fe3d3572a41010cd38c

**Comment by danjwinter** [comment]
Respond in the comments of this issue with:
1. What is something you learned that was particularly surprising/interesting?
The most interesting thing I learned was the part about namespaced event binding. It's great because now you can couple event based callbacks with other environmental variables and bind/unbind only the ones that are appropriate without getting confused as to which event binding you are referring to.
1. What was something you already knew?
   I already knew the basic way to query the DOM for certain classes using $('.CLASS_NAME').
2. Was there anything you feel you still don't understand?
   I'm still not sure the best way to organize my code. It feels like a big jumble since I'm not really using OOP.

Feel free to ask any questions about jQuery fundamentals here as well.

**Comment by slota** [comment]
1. What is something you learned that was particularly surprising/interesting?
2. I think custom effects with .animate() is pretty sweet, I'm excited to use this for game time!
3. What was something you already knew?
4. Basic selectors of JQuery I already understood
5. Was there anything you feel you still don't understand?
6. I don't understand a lot of it still, unfortunately I feel I really need to work on projects and refer back to this and actually start using it before I really get a firm understanding

**Comment by edgarduran** [comment]
https://gist.github.com/edgarduran/3b98a07818b870902c1c

**Comment by bethsebian** [comment]
Respond in the comments of this issue with:
_1. What is something you learned that was particularly surprising/interesting?_
- $() is an alias for $(document).ready()
- Almost everything in Javascript is treated as an object, except 5 things (strings, booleans, numbers, undefined, and null). 

_2. What was something you already knew?_
The relationship between objects and attributes and methods for calling those attributes on objects. 

_3. Was there anything you feel you still don't understand?_
Still a little shaky around the idea that JQuery interacts with views by capturing facets of the view and interacting with them as objects. In JQuery world, the JQuery creates the page dynamically and pushes information to the view and database; a totally different mindset from what we've been doing, where the page gets built in a very linear sense.

**Comment by Jlawlzz** [comment]
Interesting:
- I think it is interesting that when you isolate a view element with $() it creates a jQuery object, I had no idea that is actually how that worked.  
  - I didn't know about jQuery effect, they seem awesome! (although I am scared of using them the way I used powerpoint animations when I figured out you could do that)

Something I already know:
- I already knew a bit about getters and setters, and event listeners.

I am still confused about:
- I am still confused about the way certain objects work still.  Like .closest() works sometimes and other times does not, I have trouble finding the difference between the working and broken case as well.  I think this is something that will iron itself out as I spend more time with jQuery though!

**Comment by marlomajor** [comment]
https://gist.github.com/marlomajor/71accce888e55074f1fc
