### ISSUE TITLE
Read through the nature of Javascript

### ISSUE THREAD

**Issue by neight-allen** [turingschool/intermission-assignments#86]
Read through [Chapter 3 (Speaking): The Nature of JavaScript](http://speakingjs.com/es5/ch03.html)

Discuss in the comments

Some questions to start discussion:

What was interesting?
Which sections did you totally skim?
Do you think the reading was valuable?
Which topics were notably confusing?

**Comment by kjs222** [comment]
1.  Interesting: Recognizing that it's both functional and object oriented.
2. Skimmed: influences.  If I knew anything about any of the influences, then I may have paid attention, because I could have drawn parallels.  Alas, I do not.
3. Valuable? A bit.  I would appreciate a bit more depth on the points raised.  
4.  Confusing: Nothing was confusing, because nothing was really explained.  If they explained closures, I would have been confused.  :)

**Comment by roscalabrin** [comment]
**What was interesting?**
1. That unlike other programming languages JavaScript has only one type of number (64-bit Floating Point vs. float, integer, etc.).
2. That JavaScript is both a functional and object-oriented language.
3. The explanation that JavaScript fails silently because it couldn't throw exceptions at the beginning.
**Which sections did you totally skim?**
Nothing really. It was a short read.
**Do you think the reading was valuable?**
Yes, in the sense that raised more questions about JavaScript that I want to understand in more depth. 
**Which topics were notably confusing?**
Elegant Parts. It wasn't clear to me why those are the elegant parts, and how they work. Although, I think that the point of the text was just to highlight them.

**Comment by ryanflach** [comment]
1. That JS fails silently due to it not having exception handling until ES3.
2. I didn't skim any of this reading.
3. Yes, I do think that it was valuable. It raised more questions than it answered, and I'll look forward to connecting the dots in future lessons or projects.
4. Not much was explained in depth, and as a result there were several topics thrown around that I don't have a firm grasp on (e.g., first-class functions, closures, partial application via `bind()`, etc.).

**Comment by dtinianow** [comment]
I thought it was especially interesting to learn that JavaScript is both a functional and object oriented programming language.  I also found it interesting how many different languages have influenced the creation of JS.  I didn't skim any sections of this.  I found this article valuable to help  ascertain some of the defining characteristics of JS, as well as to see what parts of JS derive from other languages.  The article itself was not confusing, although many JS topics were mentioned in the abstract and left unexplained.

**Comment by kbs5280** [comment]
Read through Chapter 3 (Speaking): The Nature of JavaScript
Discuss in the comments
Some questions to start discussion:

What was interesting?
It’s interesting that JS is both functional and object-oriented, and to revisit what those mean in practical and conceptual terms. The various influences on the development of the language was also interesting.

 Which sections did you totally skim?
I didn’t skim any particular section, but will have to read more about first-class functions, closures and prototypes…

 Do you think the reading was valuable?
Yes. I’ve read most of it before, but being re-introduced to these concepts is always valuable.

 Which topics were notably confusing? 
Nothing was notably confusing. There were mention of a few unfamiliar concepts that I can look into further.

**Comment by cconcannon** [comment]
I agree with many of the statements above about JavaScript being both object-oriented and functional, but I don't necessarily know hard differences between those two yet except that functional programming supports immutable data structures. I would like to learn more about the different JavaScript engines. 

I skimmed the majority of chapter 1 because I began reading this after doing many exercises in JavaScript, so I understood how to do math operations and declare functions and conditional statements. I think the reading was valuable but needs supplemental exercises.

**Comment by Automatic365** [comment]
I thought it was interesting how many influences went into the creation of Javascript. I'm also interested in finding ways to take advantage of the functional/OO aspects of JS. I would also like a better understanding of the Elegant parts.

**Comment by allindow** [comment]
What was interesting?
**Even though javascript errors are sometimes confusing and downright misleading, it initially didn't throw any exceptions at all. So...better than nothing? After learning Ruby, Javascript is really unattractive to me, and it generally blows my mind that a language that was built in 10 days is the most popular coding language in the world. Trying to embrace it...**

Which sections did you totally skim?
**It wasn't very long or heavy so, none**

Do you think the reading was valuable?
**I think so. Having some declarations about what Javascript is and is about has made me more interested in it.**
Which topics were notably confusing?
**The quirk fixes. I'm not sure what the arrays being too flexible means.**

**Comment by zackforbing** [comment]
**What was interesting?** JS's pulling of concepts from many different languages
**Which sections did you totally skim?** none; it was short enough.
**Do you think the reading was valuable?** the summarization of JS's nature was definitely worth the price of admission.
**Which topics were notably confusing?** first-class functions and closures, as they weren't really defined in the reading. the part about Arrays being too flexible was confusing as well.

**Comment by chompasina** [comment]
What was interesting? I didn't realize so many languages had contributed to JavaScript's form.
Which sections did you totally skim? I didn't exactly skim, but I didn't look up everything I didn't know, so the elegant parts feels like I skimmed it. I don't know what 'first-class functions', 'closures', or really what 'prototypes' are.
Do you think the reading was valuable? No. I think we should have had a better overview required instead.
Which topics were notably confusing? Unorthodox features felt too brief and in fact, this reading was entirely too brief to be beneficial, in my honest opinion.

**Comment by MsJennyGiraffe** [comment]
I think it's really interesting that in javascript there are no integers, just floating points. I didn't realize.
I wish the article got into why prototypes are considered elegant, and what is exactly meant by that. I thought that you can add a method to an object by calling prototype on the class, but I don't quite understand what's elegant about that. I also wish it got into what closures are, because I have no idea what they are. I got a little confused when it talked about arrays being too flexible and that there can be holes in arrays. Would that be like Ruby where you can have nil in an array and it has an index? 
Overall, I do think the reading was valuable, it was a nice and brief summary of the language.

**Comment by deborahleehamel** [comment]
### What was interesting?

This was not a deep dive, but I liked the summary format and liked overview perspective with highlights. Like other's mentioned, the melting pot evolution for Javascript is interesting. I especially liked how they attributed specific functional components to different languages.

### Which sections did you totally skim?

None. It was very brief anyway. Even checked out the link to Chapter 32 that gives overview for Linting, Unit Testing and Minification, Building and Scaffolding.

### Do you think the reading was valuable?

Yes.

### Which topics were notably confusing?

Some of the things from functional programming paradigms like first-class functions, closures and prototypes. No in-depth explanations or practice here.

**Comment by karinamzalez** [comment]
- What was interesting: That JavaScript is deployed as source-code.  Although at Turing we've learned the basics of Back-end programming, I feel as if there's this other enigmatic world of programming where languages get created-- it intrigues me. 
- What sections did you totally skim:  The chapter was very short in general, so in an ideal world I wouldn't have skimmed anything-- but I wasn't very familiar with the influences so I blanked a bit on that bit.  
- Do you think the reading was valuable:  The reading was very succinct, it would have been neat if it went a bit more in depth on some things.. I feel like this was written for someone who has a decent background of understanding or a mad-skilled googler (which I suppose go hand-in-hand). 
- Which topics where notably confusing: They only explained two out of the five 'elegant parts' and then explain that those elegant parts _obviously_ pick up the slack of the not-so-elegant parts.. more depth would have been neat.

**Comment by 5Notes** [comment]
1. What was interesting?
   AWK inspired JavaScript’s functions. In fact, the keyword function comes from AWK.
2. Which sections did you totally skim?
   'JavaScript’s nature can be summarized as follows:' section.
3. Do you think the reading was valuable?
   Influences of Javascript.
4. Which topics were notably confusing?
   What they meant exactly by "Quirks and Unorthodox Features".

**Comment by matthewrpacker** [comment]
What was interesting?
_The number of languages that influenced JavaScript.  It would be interesting to learn why they chose each language._

Which sections did you totally skim?
_N/A_

Do you think the reading was valuable?
_I wouldn't characterize it as valuable.  Some parts were interesting, but I don't think I gained anything substantial by reading the article._

Which topics were notably confusing?
_Why the elegant parts of JavaScript are considered elegant._

**Comment by Laner12** [comment]
What was interesting?
The article as a whole, I liked the background information.
Which sections did you totally skim?
N/A
Do you think the reading was valuable?
I don't know if it was valuable but it was interesting
Which topics were notably confusing?
Why elegant parts are classified

**Comment by twhitinger** [comment]
What was interesting?
The fact the entire web is actually based on javascript is a cruel joke. Prototypal inheritance is kind of like monkey patching in ruby and its cool.
Which sections did you totally skim?
Influences
Do you think the reading was valuable?
I think it was a ok brief intro, though I had knowledge of most of it.
What topics were notably confusing.
That the web is so dependent on javascript....WTF
